---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svcacount
secrets:
  - name: svcaccount-test

---
apiVersion: v1
kind: Secret
metadata:
  name: svcaccount-test
type: kubernetes.io/service-account-token
data:
  token: 'test'